language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  except:
    - 3.3.2
    - v5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit